version: 2.1

parameters:
  slack-mentions:
    type: string
    default: 'afiune,scottford'
  only_for_branches:
    type: string
    default: 'master'

orbs:
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.1.0

executors:
  terraform:
    docker:
      - image: techallylw/terraform:latest
  alpine:
    docker:
      - image: cibuilds/base:latest
    resource_class: small

jobs:
  terraform-test:
    executor: terraform
    steps:
      - checkout
      - run: scripts/ci_tests.sh
      - slack/status:
          fail_only: true
          mentions: << pipeline.parameters.slack-mentions >>
          only_for_branches: <<pipeline.parameters.only_for_branches>>
  verify-release:
    executor: alpine
    steps:
      - checkout
      - run: scripts/release.sh verify
  trigger-release:
    executor: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cc:af:52:93:95:48:fd:88:0d:ca:13:c7:a2:26:4e:6c"
      - run: scripts/release.sh trigger
  release:
    executor: alpine
    steps:
      - checkout
      - jq/install
      - slack/notify:
          mentions: << pipeline.parameters.slack-mentions >>
          message: Releasing new version of this repository
      - run: scripts/release.sh publish
      - slack/status:
          mentions: << pipeline.parameters.slack-mentions >>

workflows:
  version: 2
  test-trigger-release:
    jobs:
      - terraform-test
      - trigger-release:
          requires:
            - terraform-test
          filters:
            branches:
              only: master

  verify-release:
    jobs:
      - verify-release:
          filters:
             branches:
               only: release

  release-from-tag:
    jobs:
      - release:
          filters:
            tags:
               only: /^v.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: master
    jobs:
      - terraform-test
